services:
  - type: web
    name: meridian-news-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: CURRENTS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DID_API_KEY
        sync: false
